version: "3.9"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
  web:
    build:
      context: ../web
    ports:
      - "80:3000"
  api:
    build:
      context: ../api
    ports:
      - "8080:8080"
