version: "3.9"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
  api:
    build:
      context: ../api
    depends_on:
      - db
    ports:
      - "8080:8080"
  web:
    build:
      context: ../web
    depends_on:
      - api
    ports:
      - "80:3000"
